### ISSUE TITLE
A (maybe) better UI

### ISSUE THREAD

**Issue by erichuang1994** [timqian/my-headline-crawler#1]
It's a  attractive project.So I spent some time on it tonight.
Then I get http://erichuang1994.me/my-headline/index.html.
Can I open a  pr?

**Comment by timqian** [comment]
@erichuang1994 Thanks for your attention of this project.. The arrows are apparently better. You are welcomed to open a pr at [my-headline](https://github.com/timqian/my-headline) project.
![image](https://cloud.githubusercontent.com/assets/5512552/14433151/b790513a-003f-11e6-8bd5-672fa30927bd.png)

**Comment by erichuang1994** [comment]
有个问题，我不知道该怎么把我的代码合并到你的里面去。我是自己重新写了个页面然后用的还是你的数据。:)

**Comment by timqian** [comment]
恩，看了你的代码，已经用上你的箭头了，还是第一次用 unicode 字符集的符号，学习了。
颜色我先不改了，这个项目暂时主要还是自用。
crawler 里面的 data 我会在每天 0：30分更新（准备搞个 amazon vps 用 cron 每天自动跑），随便用好了。

**Comment by timqian** [comment]
更新了下 my-headline 的 [readme](https://github.com/timqian/my-headline) 方便  setup
